# Generated by Django 5.1.3 on 2024-11-12 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Women', 'Women'), ('Men', 'Men'), ('Kids', 'Kids')], max_length=50),
        ),
    ]
