# Generated by Django 5.1.3 on 2024-11-13 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_delete_category_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ratings',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
